before_install:
- openssl aes-256-cbc -K $encrypted_304654daeaee_key -iv $encrypted_304654daeaee_iv
  -in deploy_rsa.enc -out ~\/.ssh/deploy_rsa -d
- curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
- sudo dpkg -i hugo_0.55.4_Linux-64bit.deb
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "Host aboni.dev\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- mkdir /tmp/ssh
- touch /tmp/ssh/deploy_rsa
- openssl aes-256-cbc -K $encrypted_dded3a778621_key -iv $encrypted_dded3a778621_iv
  -in deploy_rsa.enc -out /tmp/ssh/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/ssh/deploy_rsa
- ssh-add /tmp/ssh/deploy_rsa
- ssh -i /tmp/ssh/deploy_rsa travis@aboni.dev pwd
script:
- hugo
install:
- ls
- rsync -r  -v --stats --progress --delete-after ./public travis@aboni.dev:/www/elciber
