baseURL = "https://elciber.ga/"
languageCode = "es"
title = "El Ciber"
theme = "hyde-hyde"
summarylength = 60
paginate = 5
disqusShortname = "elciberga" 


## Site Settings
[params]
    author = "Author"
    title = "Title"
    description = "~ A llorar a la iglesia ~ "
    authorimage = "/img/cod02.png"
    dateformat = "02/01/2006"

    # sidebar, copyright & license
    copyright = "AJB"
    license = "WTFPL"
    licenseURL = "http://www.wtfpl.net/"
    showBuiltWith = false
    showComments = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

    postNavigation = false

## Main Menu
[[menu.main]]
    name = "Inicio"
    weight = 100
    identifier = "home"
    url = "/"
[[menu.main]]
    name = "Reglas"
    identifier = "reglas"
    weight = 200
    url = "/reglas/"
[[menu.main]]
    name = "Juegos"
    identifier = "juegos"
    weight = 300
     url = "/juegos/"


